FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


COPY --chown=airflow:root requirements-base.txt ./
USER airflow
RUN pip install --no-cache-dir -r requirements-base.txt \
    && rm -rf ~/.cache/pip/* 