dbt_reddit_summary_local:
  outputs:
    dev:
      type: postgres
      threads: 1  # You can adjust this for parallel processing
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: processed_data
  target: dev