mappings:
  # Ingest and Preprocess metrics
  - match: "airflow.reddit.ingest_preprocess.processed_posts"
    name: "reddit_ingest_preprocess_posts_total"
    type: "gauge"
    help: "Total number of posts processed in the ingest phase"
    
  - match: "airflow.reddit.ingest_preprocess.total_summaries"
    name: "reddit_ingest_preprocess_summaries_total"
    type: "gauge"
    help: "Total number of summaries generated in the preprocess phase"
    
  - match: "airflow.reddit.ingest_preprocess.current_attempt"
    name: "reddit_ingest_preprocess_attempt"
    type: "gauge"
    help: "Current attempt number for the ingest and preprocess task"
    
  - match: "airflow.reddit.ingest_preprocess.success"
    name: "reddit_ingest_preprocess_success_total"
    type: "counter"
    help: "Number of successful ingest and preprocess task completions"
    
  - match: "airflow.reddit.ingest_preprocess.retry"
    name: "reddit_ingest_preprocess_retry_total"
    type: "counter"
    help: "Number of retries for the ingest and preprocess task"
    
  - match: "airflow.reddit.ingest_preprocess.error"
    name: "reddit_ingest_preprocess_error_total"
    type: "counter"
    help: "Number of errors in the ingest and preprocess task"
    
  - match: "airflow.reddit.ingest_preprocess.duration"
    name: "reddit_ingest_preprocess_duration_seconds"
    type: "timing"
    help: "Duration of the ingest and preprocess task in seconds"
    timer_type: "histogram"
    buckets: [10, 30, 60, 120, 300, 600, 1800]
    

 
  
  # Summarization metrics
  - match: "airflow.reddit.summarize.summaries_added"
    name: "reddit_summarize_summaries_added"
    type: "gauge"
    help: "Number of summaries successfully added"
    
  - match: "airflow.reddit.summarize.short_comments"
    name: "reddit_summarize_short_comments"
    type: "gauge"
    help: "Number of comments that were too short to need summarization"
    
  - match: "airflow.reddit.summarize.total_processed"
    name: "reddit_summarize_total_processed"
    type: "gauge"
    help: "Total number of comments processed"
    
  - match: "airflow.reddit.summarize.current_attempt"
    name: "reddit_summarize_attempt"
    type: "gauge"
    help: "Current attempt number for the summarize task"
    
  - match: "airflow.reddit.summarize.success"
    name: "reddit_summarize_success_total"
    type: "counter"
    help: "Number of successful summarize task completions"
    
  - match: "airflow.reddit.summarize.retry"
    name: "reddit_summarize_retry_total"
    type: "counter"
    help: "Number of retries for the summarize task"
    
  - match: "airflow.reddit.summarize.error"
    name: "reddit_summarize_error_total"
    type: "counter"
    help: "Number of errors in the summarize task"
    
  - match: "airflow.reddit.summarize.duration"
    name: "reddit_summarize_duration_seconds"
    type: "timing"
    help: "Duration of the summarize task in seconds"
    timer_type: "histogram"
    buckets: [10, 30, 60, 120, 300, 600, 1800]
    
    
  # Sentiment Analysis metrics
  - match: "airflow.reddit.sentiment.processed"
    name: "reddit_sentiment_processed_total"
    type: "gauge"
    help: "Number of comments processed for sentiment analysis"
    
  - match: "airflow.reddit.sentiment.current_attempt"
    name: "reddit_sentiment_attempt"
    type: "gauge"
    help: "Current attempt number for the sentiment analysis task"
    
  - match: "airflow.reddit.sentiment.success"
    name: "reddit_sentiment_success_total"
    type: "counter"
    help: "Number of successful sentiment analysis task completions"
    
  - match: "airflow.reddit.sentiment.retry"
    name: "reddit_sentiment_retry_total"
    type: "counter"
    help: "Number of retries for the sentiment analysis task"
    
  - match: "airflow.reddit.sentiment.error"
    name: "reddit_sentiment_error_total"
    type: "counter"
    help: "Number of errors in the sentiment analysis task"
    
  - match: "airflow.reddit.sentiment.duration"
    name: "reddit_sentiment_duration_seconds"
    type: "timing"
    help: "Duration of the sentiment analysis task in seconds"
    timer_type: "histogram"
    buckets: [10, 30, 60, 120, 300, 600, 1800]
    
    
  # Join Operation metrics
  - match: "airflow.reddit.join.rows_processed"
    name: "reddit_joined_table_rows"
    type: "gauge"
    help: "Total number of rows in the joined_summary_analysis table"
    
  - match: "airflow.reddit.join.current_attempt"
    name: "reddit_join_attempt"
    type: "gauge"
    help: "Current attempt number for the join operation"
    
  - match: "airflow.reddit.join.success"
    name: "reddit_join_success_total"
    type: "counter"
    help: "Number of successful DBT join model runs"
    
  - match: "airflow.reddit.join.retry"
    name: "reddit_join_retry_total"
    type: "counter"
    help: "Number of retries for the DBT join model"
    
  - match: "airflow.reddit.join.error"
    name: "reddit_join_error_total"
    type: "counter"
    help: "Number of errors in the DBT join model execution"
    
  - match: "airflow.reddit.join.duration"
    name: "reddit_join_model_duration_seconds"
    type: "timing"
    help: "Duration of the DBT join model execution in seconds"
    timer_type: "histogram"
    buckets: [10, 30, 60, 120, 300, 600, 1800]
    
    
    # Update Processing Status
  - match: "airflow.reddit.processing_status.duration"
    name: "reddit_processing_status_duration"
    help: "Duration of processing status update in milliseconds"
    type: "timing"
    timer_type: "histogram"
    buckets: [10, 30, 60, 120, 300, 600, 1800]
    
  
  - match: "airflow.reddit.processing_status.rows_processed"
    name: "reddit_processing_status_rows"
    help: "Number of rows processed in status update"
    type: "gauge"
    
  - match: "airflow.reddit.processing_status.current_attempt"
    name: "reddit_processing_status_attempt"
    help: "Current attempt number for processing status update"
    type: "gauge"
    
  - match: "airflow.reddit.processing_status.success"
    name: "reddit_processing_status_success_total"
    help: "Total successful processing status updates"
    type: "counter"
    
  - match: "airflow.reddit.processing_status.retry"
    name: "reddit_processing_status_retry_total"
    help: "Total retried processing status updates"
    type: "counter"
    
  - match: "airflow.reddit.processing_status.error"
    name: "reddit_processing_status_error_total"
    help: "Total errors in processing status updates"
    type: "counter"

  # Gemini Metrics
  - match: "airflow.reddit.gemini.outputs_generated"
    name: "reddit_gemini_outputs"
    help: "Number of markdown files generated by Gemini"
    type: "gauge"
    
  - match: "airflow.reddit.gemini.subreddits_processed"
    name: "reddit_gemini_subreddits"
    help: "Number of subreddits processed by Gemini"
    type: "gauge"
    
  - match: "airflow.reddit.gemini.current_attempt"
    name: "reddit_gemini_attempt"
    help: "Current attempt number for Gemini task"
    type: "gauge"
    
  - match: "airflow.reddit.gemini.duration"
    name: "reddit_gemini_duration"
    help: "Duration of Gemini task execution in milliseconds"
    type: "timing"
    timer_type: "histogram"
    buckets: [10, 30, 60, 120, 300, 600, 1800]
    
    
  - match: "airflow.reddit.gemini.success"
    name: "reddit_gemini_success_total"
    help: "Total successful Gemini task executions"
    type: "counter"
    
  - match: "airflow.reddit.gemini.retry"
    name: "reddit_gemini_retry_total"
    help: "Total retried Gemini task executions"
    type: "counter"
    
  - match: "airflow.reddit.gemini.error"
    name: "reddit_gemini_error_total"
    help: "Total errors in Gemini task executions"
    type: "counter"

  # DBT Test Metrics
  - match: "airflow.reddit.dbt.test_raw_sources.tests.passed"
    name: "reddit_dbt_raw_sources_tests_passed"
    type: "gauge"
    help: "Number of DBT tests that passed for raw sources"

  - match: "airflow.reddit.dbt.test_raw_sources.tests.failed"
    name: "reddit_dbt_raw_sources_tests_failed"
    type: "gauge"
    help: "Number of DBT tests that failed for raw sources"

  - match: "airflow.reddit.dbt.test_staging_models.tests.passed"
    name: "reddit_dbt_staging_models_tests_passed"
    type: "gauge"
    help: "Number of DBT tests that passed for staging models"

  - match: "airflow.reddit.dbt.test_staging_models.tests.failed"
    name: "reddit_dbt_staging_models_tests_failed"
    type: "gauge"
    help: "Number of DBT tests that failed for staging models"

  - match: "airflow.reddit.dbt.test_summarize_models.tests.passed"
    name: "reddit_dbt_summarize_models_tests_passed"
    type: "gauge"
    help: "Number of DBT tests that passed for summarize models"

  - match: "airflow.reddit.dbt.test_summarize_models.tests.failed"
    name: "reddit_dbt_summarize_models_tests_failed"
    type: "gauge"
    help: "Number of DBT tests that failed for summarize models"

  - match: "airflow.reddit.dbt.test_sentiment_analysis.tests.passed"
    name: "reddit_dbt_sentiment_analysis_tests_passed"
    type: "gauge"
    help: "Number of DBT tests that passed for sentiment analysis"

  - match: "airflow.reddit.dbt.test_sentiment_analysis.tests.failed"
    name: "reddit_dbt_sentiment_analysis_tests_failed"
    type: "gauge"
    help: "Number of DBT tests that failed for sentiment analysis"

  - match: "airflow.reddit.dbt.test_joined_summary_analysis.tests.passed"
    name: "reddit_dbt_joined_summary_analysis_tests_passed"
    type: "gauge"
    help: "Number of DBT tests that passed for joined summary analysis"

  - match: "airflow.reddit.dbt.test_joined_summary_analysis.tests.failed"
    name: "reddit_dbt_joined_summary_analysis_tests_failed"
    type: "gauge"
    help: "Number of DBT tests that failed for joined summary analysis"

  - match: "airflow.reddit.dbt.test_update_processing_status.tests.passed"
    name: "reddit_dbt_update_processing_status_tests_passed"
    type: "gauge"
    help: "Number of DBT tests that passed for update processing status"

  - match: "airflow.reddit.dbt.test_update_processing_status.tests.failed"
    name: "reddit_dbt_update_processing_status_tests_failed"
    type: "gauge"
    help: "Number of DBT tests that failed for update processing status"

